language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/database.example.yml config/database.yml
  - cp config/oauth.example.yml config/oauth.yml
  - bundle exec rake db:create db:migrate db:test:prepare
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - RAILS_ENV=test bundle exec rake spec:travis

branches:
  only:
    - master
